# Latexmk configuration for course report
$pdf_mode = 5;  # use xelatex
$xelatex = "xelatex -interaction=nonstopmode -halt-on-error -synctex=1 %O %S";
$bibtex_use = 2;
$clean_ext = "synctex.gz acn acr alg aux bbl bcf blg brf fdb_latexmk glg glo gls idx ilg ind ist lof log lot out run.xml toc dvi";
